[[headers]]
  for = "/*.(js|css|map|png)"

  [headers.values]
    cache-control = '''
    public,
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/sw.js"

  [headers.values]
    cache-control = '''
    public,
    max-age=0,
    must-revalidate'''

[[headers]]
  for = "/sw-esm.js"

  [headers.values]
    cache-control = '''
    public,
    max-age=0,
    must-revalidate'''

[[headers]]
  for = "/(sw|sw-esm).js.map"

  [headers.values]
    cache-control = '''
    public,
    max-age=0,
    must-revalidate'''

[[headers]]
  for = "/assets/**/*.png"

  [headers.values]
    cache-control = '''
    public,
    max-age=600,
    must-revalidate'''

[[headers]]
  for = "/favicon.ico"

  [headers.values]
    cache-control = '''
    public,
    max-age=600,
    must-revalidate'''
